### ISSUE TITLE
rmm - failures in test_failure_callback_resource_adaptor

### ISSUE THREAD

**Issue by fondaing** [rapidsai/build-planning#121]
SM100 failures:

=================================== FAILURES ===================================
____________________ test_failure_callback_resource_adaptor ____________________
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/usr/local/lib/python3.10/dist-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.10/dist-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/root/rmm/python/rmm/rmm/tests/test_rmm.py", line 803, in test_failure_callback_resource_adaptor
    with pytest.raises(MemoryError):
  File "/usr/local/lib/python3.10/dist-packages/_pytest/python_api.py", line 987, in __exit__
    fail(self.message)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/outcomes.py", line 198, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: DID NOT RAISE <class 'MemoryError'>
_________________ test_failure_callback_resource_adaptor_error _________________
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/usr/local/lib/python3.10/dist-packages/_pytest/runner.py", line 262, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/runner.py", line 169, in pytest_runtest_call
    item.runtest()
  File "/usr/local/lib/python3.10/dist-packages/_pytest/python.py", line 1792, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 182, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_result.py", line 100, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/usr/local/lib/python3.10/dist-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/python.py", line 194, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "/root/rmm/python/rmm/rmm/tests/test_rmm.py", line 840, in test_failure_callback_resource_adaptor_error
    with pytest.raises(RuntimeError, match="MyError"):
  File "/usr/local/lib/python3.10/dist-packages/_pytest/python_api.py", line 987, in __exit__
    fail(self.message)
  File "/usr/local/lib/python3.10/dist-packages/_pytest/outcomes.py", line 198, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: DID NOT RAISE <class 'RuntimeError'>
=========================== short test summary info ============================
FAILED rmm/tests/test_rmm.py::test_failure_callback_resource_adaptor - Failed...
FAILED rmm/tests/test_rmm.py::test_failure_callback_resource_adaptor_error - ...
============ 2 failed, 791 passed, 393 skipped in 143.11s (0:02:23) ============

**Comment by harrism** [comment]
@fondaing can you include version information? Do you have the latest 24.12? Because I just merged a PR to fix this issue yesterday. https://github.com/rapidsai/rmm/pull/1734

If you are using 24.10 that would explain things. Otherwise my fix must not have been sufficient and I would need more details.

**Comment by harrism** [comment]
BTW, this really should be an issue in the RMM repo, since it's not related to planning across multiple repos.  Should just reopen this issue if the problem persists: https://github.com/rapidsai/rmm/issues/1733

**Comment by robertmaynard** [comment]
Backport PR: https://gitlab-master.nvidia.com/RAPIDS/dlfw/-/merge_requests/208
